title: Brian Yee # your site title
author: Brian Yee
email: brian.ph.yee@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  The personal portfolio of Brian Yee including machine learning,
  data visualization and contact information.
baseurl: "/" # the subpath of your site, e.g. /blog
# if I put / all my images work, if I make it an empty string it is restored to what it was originally
url: "http://brian-yee.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  brian-yee # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer
social:
  name: Brian Yee
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

disqus:
  shortname: brian-yee # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
